GET http://localhost:5000/survey
Content-Type: application/json

###

GET http://localhost:5000/survey/18
Content-Type: application/json

###
PUT http://localhost:5000/survey/9
Content-Type: application/json

{
    "survey_id": 18,
    "questions": [
        {"question_id": 13, "choice": 14},
        {"question_id": 14, "choice": 16}
    ]
}

### Send POST request with json body

POST http://localhost:5000/survey
Content-Type: application/json

{
    "name": "Dogs",
    "questions": [{
        "text": "What is your favorite dog?",
        "choices": [
            { "text": "Bull" },
            { "text": "German" },
            { "text": "Street" }]
    }, {
        "text": "What is your second favorite dog?",
        "choices": [
            { "text": "Bull" },
            { "text": "German" },
            { "text": "Street" }]
    }]
}

###




