GET http://localhost:5000/survey
Content-Type: application/json

###

GET http://localhost:5000/survey/1
Content-Type: application/json

###
PUT http://localhost:5000/survey/9
Content-Type: application/json

{
    "id": 1,
    "name": "Cards",
    "questions": [
        {"id": 1, "choice": 1},
        {"id": 2, "choice": 5}
    ]
}

### Send POST request with json body

POST http://localhost:5000/survey
Content-Type: application/json

{
    "name": "Cars",
    "questions": [{
        "text": "What is your favorite car?",
        "choices": [
            { "text": "Corvette" },
            { "text": "Mustang" },
            { "text": "Camaro" }]
    }, {
        "text": "What is your second favorite car?",
        "choices": [
            { "text": "Corvette" },
            { "text": "Mustang" },
            { "text": "Camaro" }]
    }]
}

###




